const {v4: uuid} = require('uuid');

let ammo = [
    {
        name: "5.25mm Buckshot",
        gauge: "12ga",
        type: "Buckshot",
        damage: 296,
        penPower: 1,
        armorDmg: "15%",
        accuracy: "",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c4/12x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
        name: "8.5mm Magnum Buckshot",
        gauge: "12ga",
        type: "Buckshot",
        damage: 400,
        penPower: 2,
        armorDmg: "26%",
        accuracy: "-15%",
        recoil: "+115%",
        fragChance: "0%",
        lightBleed: "20%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c4/12x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
        name: "6.5mm Express Buckshot",
        gauge: "12ga",
        type: "Buckshot",
        damage: 315,
        penPower: 3,
        armorDmg: "26%",
        accuracy: "+15%",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c4/12x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
        name: "7mm Buckshot",
        gauge: "12ga",
        type: "Buckshot",
        damage: 312,
        penPower: 3,
        armorDmg: "26%",
        accuracy: "",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c4/12x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
        name: "Flechette",
        gauge: "12ga",
        type: "Buckshot",
        damage: 200,
        penPower: 31,
        armorDmg: "26%",
        accuracy: "-10%",
        recoil: "",
        fragChance: "0%",
        lightBleed: "25%",
        heavyBleed: "25%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "very effective",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/05/12-70_Flechette.png",
        _id: uuid()
    },
    {
        name: "RIP",
        gauge: "12ga",
        type: "Slug",
        damage: 265,
        penPower: 2,
        armorDmg: "11%",
        accuracy: "+80%",
        recoil: "+35%",
        fragChance: "100%",
        lightBleed: "40%",
        heavyBleed: "25%",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/43/12x70ripimg.png",
        _id: uuid()
    },
    {
        name: "SuperFormance HP Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 220,
        penPower: 5,
        armorDmg: "12%",
        accuracy: "+170%",
        recoil: "-15%",
        fragChance: "39%",
        lightBleed: "30%",
        heavyBleed: "40%",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/97/12-70_HP_SF.png",
        _id: uuid()
    },
    {
        name: "Grizzly 40 Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 190,
        penPower: 12,
        armorDmg: "48%",
        accuracy: "+80%",
        recoil: "+20%",
        fragChance: "12%",
        lightBleed: "",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/90/1270Grizzly40Slug.png",
        _id: uuid()
    },
    {
        name: "Copper Sabot Premier Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 206,
        penPower: 14,
        armorDmg: "46%",
        accuracy: "+150%",
        recoil: "+10%",
        fragChance: "38%",
        lightBleed: "35%",
        heavyBleed: "25%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "slightly effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/58/12x70SLUG_CSP.png",
        _id: uuid()
    },
    {
        name: "Lead Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 162,
        penPower: 15,
        armorDmg: "55%",
        accuracy: "+120%",
        recoil: "",
        fragChance: "20%",
        lightBleed: "10%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/be/12x70SLUGIMAGE.png",
        _id: uuid()
    },
    {
        name: "Poleva-3 Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 140,
        penPower: 17,
        armorDmg: "40%",
        accuracy: "+110%",
        recoil: "-15%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e6/Poleva3.png",
        _id: uuid()
    },
    {
        name: "Dual Sabot Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 170,
        penPower: 17,
        armorDmg: "65%",
        accuracy: "+100%",
        recoil: "+15%",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "magdump only",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/d/d5/12-70_Dual_Sabot.png",
        _id: uuid()
    },
    {
        name: "FTX Custom Lite Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 183,
        penPower: 20,
        armorDmg: "50%",
        accuracy: "+135%",
        recoil: "-25%",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "magdump only",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/f6/FTX_Slug.png",
        _id: uuid()
    },
    {
        name: "Poleva-6u Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 150,
        penPower: 20,
        armorDmg: "50%",
        accuracy: "+115%",
        recoil: "-15%",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "5%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "magdump only",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/54/1270Poleva6Slug.png",
        _id: uuid()
    },
    {
        name: ".50 BMG Bullet",
        gauge: "12ga",
        type: "Slug",
        damage: 197,
        penPower: 26,
        armorDmg: "57%",
        accuracy: "+90%",
        recoil: "+25%",
        fragChance: "5%",
        lightBleed: "",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "slightly effective",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/d/d4/12-70_.50_BMG.png",
        _id: uuid()
    },
    {
        name: "AP-20 Slug",
        gauge: "12ga",
        type: "Slug",
        damage: 164,
        penPower: 37,
        armorDmg: "65%",
        accuracy: "+80%",
        recoil: "+50%",
        fragChance: "3%",
        lightBleed: "",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/ad/12-70_AP-20.png",
        _id: uuid()
    },
    {
        name: "5.6mm Buckshot",
        gauge: "20ga",
        type: "Buckshot",
        damage: 208,
        penPower: 1,
        armorDmg: "12%",
        accuracy: "-10%",
        recoil: "+10%",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/08/20x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
	    name: "6.2mm Buckshot",
        gauge: "20ga",
        type: "Buckshot",
        damage: 176,
        penPower: 2,
        armorDmg: "13%",
        accuracy: "",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/08/20x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
	    name: "7.5mm Buckshot",
        gauge: "20ga",
        type: "Buckshot",
        damage: 200,
        penPower: 3,
        armorDmg: "14%",
        accuracy: "",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/08/20x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
	    name: "7.3mm Buckshot",
        gauge: "20ga",
        type: "Buckshot",
        damage: 207,
        penPower: 3,
        armorDmg: "13%",
        accuracy: "",
        recoil: "+15%",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slightly effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/08/20x70BUCKSHOTIMAGE.png",
        _id: uuid()
    },
    {
	    name: "Devastator Slug",
        gauge: "20ga",
        type: "Slug",
        damage: 198,
        penPower: 5,
        armorDmg: "13%",
        accuracy: "+125%",
        recoil: "+30%",
        fragChance: "100%",
        lightBleed: "20%",
        heavyBleed: "30%",
        effectiveness: {
            lvl1: "its possible but unlikely",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/58/2070DevastatorSlug.png",
        _id: uuid()
    },
    {
	    name: "Poleva-3 Slug",
        gauge: "20ga",
        type: "Slug",
        damage: 120,
        penPower: 14,
        armorDmg: "35%",
        accuracy: "+110%",
        recoil: "-15%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/67/70x20SLUG_poleva3.png",
        _id: uuid()
    },
    {
	    name: "Star Slug",
        gauge: "20ga",
        type: "Slug",
        damage: 154,
        penPower: 16,
        armorDmg: "42%",
        accuracy: "+130%",
        recoil: "+5%",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "30%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/be/20-70_Star_Slug.png",
        _id: uuid()
    },
    {
	    name: "Poleva-6u Slug",
        gauge: "20ga",
        type: "Slug",
        damage: 135,
        penPower: 17,
        armorDmg: "40%",
        accuracy: "+110%",
        recoil: "-10%",
        fragChance: "15%",
        lightBleed: "",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/b1/20x70SLUG_poleva6u.png",
        _id: uuid()
    },
    {
        name: "Zvezda Flashbang Round",
        gauge: "23ga",
        type: "Buckshot",
        damage: 0,
        penPower: 0,
        armorDmg: "0%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/0f/23x75_Star_ins.png",
        _id: uuid()
    },
    {
        name: "Shrapnel-25 Buckshot",
        gauge: "23ga",
        type: "Buckshot",
        damage: 624,
        penPower: 10,
        armorDmg: "20%",
        accuracy: "+20%",
        recoil: "+10%",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/53/Shr25View.png",
        _id: uuid()
    },
    {
        name: "Shrapnel-10 Buckshot",
        gauge: "23ga",
        type: "Buckshot",
        damage: 696,
        penPower: 11,
        armorDmg: "20%",
        accuracy: "",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/2/23/23x75_Shrapnel_10.png",
        _id: uuid()
    },
    {
        name: "Barrikada Slug",
        gauge: "23ga",
        type: "Slug",
        damage: 192,
        penPower: 39,
        armorDmg: "75%",
        accuracy: "-5%",
        recoil: "+25%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/48/23x75_Barricade.png",
        _id: uuid()
    },
    {
        name: "PM SP8 gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 67,
        penPower: 1,
        armorDmg: "2%",
        accuracy: "",
        recoil: "",
        fragChance: "60%",
        lightBleed: "15%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM SP7 gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 77,
        penPower: 1,
        armorDmg: "5%",
        accuracy: "",
        recoil: "",
        fragChance: "2%",
        lightBleed: "25%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PSV",
        gauge: "9x18mm",
        type: "Round",
        damage: 69 ,
        penPower: 3,
        armorDmg: "5%",
        accuracy: "",
        recoil: "",
        fragChance: "40%",
        lightBleed: "10%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM P gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 50,
        penPower: 5,
        armorDmg: "16%",
        accuracy: "",
        recoil: "",
        fragChance: "425%",
        lightBleed: "10%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "magdump only",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PSO gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 54,
        penPower: 5,
        armorDmg: "13%",
        accuracy: "+10%",
        recoil: "",
        fragChance: "45%",
        lightBleed: "10%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "magdump only",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PS gs PPO",
        gauge: "9x18mm",
        type: "Round",
        damage: 55,
        penPower: 6,
        armorDmg: "16%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "15%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slighitly effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PRS gs",
        gauge: "9x18mm",
        type: "Round",
        damage: 58,
        penPower: 6,
        armorDmg: "16%",
        accuracy: "",
        recoil: "",
        fragChance: "30%",
        lightBleed: "15%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "slighitly effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM Ppe gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 61,
        penPower: 7,
        armorDmg: "15%",
        accuracy: "",
        recoil: "",
        fragChance: "35%",
        lightBleed: "15%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PPT gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 59,
        penPower: 8,
        armorDmg: "22%",
        accuracy: "-5",
        recoil: "-7",
        fragChance: "17%",
        lightBleed: "15%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "very effective",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM Pst gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 50,
        penPower: 12,
        armorDmg: "26%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "15%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM BZhT gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 53,
        penPower: 18,
        armorDmg: "28%",
        accuracy: "",
        recoil: "",
        fragChance: "17%",
        lightBleed: "15%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PstM gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 58,
        penPower: 24,
        armorDmg: "33%",
        accuracy: "",
        recoil: "+5",
        fragChance: "17%",
        lightBleed: "15%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "efective",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "PM PBM gzh",
        gauge: "9x18mm",
        type: "Round",
        damage: 40,
        penPower: 28,
        armorDmg: "30%",
        accuracy: "",
        recoil: "+4",
        fragChance: "16%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/ba/9x18IMAGE.png",
        _id: uuid()
    },
    {
        name: "TT LRNPC",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 66,
        penPower: 7,
        armorDmg: "27%",
        accuracy: "+10%",
        recoil: "+10%",
        fragChance: "35%",
        lightBleed: "15%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "very effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/a3/LRNPCIMAGE.png",
        _id: uuid()
    },
    {
        name: "TT LRN",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 64,
        penPower: 8,
        armorDmg: "28%",
        accuracy: "+5%",
        recoil: "-5%",
        fragChance: "35%",
        lightBleed: "15%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "very effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/a3/LRNPCIMAGE.png",
        _id: uuid()
    },
    {
        name: "TT FMJ43",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 60,
        penPower: 11,
        armorDmg: "29%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/ce/FMJ43IMAGE.png",
        _id: uuid()
    },
    {
        name: "TT AKBS",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 58,
        penPower: 12,
        armorDmg: "32%",
        accuracy: "+15%",
        recoil: "-15%",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/b8/AKBSIMAGE.png",
        _id: uuid()
    },
    {
        name: "TT P gl",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 58,
        penPower: 14,
        armorDmg: "32%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "slightly effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c1/PGLIMAGE.png",
        _id: uuid()
    },
    {
        name: "TT PT gzh",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 55,
        penPower: 18,
        armorDmg: "34%",
        accuracy: "-10%",
        recoil: "",
        fragChance: "17%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/fb/PTGZHIMAGE.png",
        _id: uuid()
    },
    {
        name: "TT Pst gzh",
        gauge: "7.62x25mm",
        type: "Round",
        damage: 50,
        penPower: 25,
        armorDmg: "36%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c5/PSTGZHIMAGE.png",
        _id: uuid()
    },
    {
        name: "RIP",
        gauge: "9x19mm",
        type: "Round",
        damage: 102,
        penPower: 2,
        armorDmg: "11%",
        accuracy: "",
        recoil: "+20%",
        fragChance: "100%",
        lightBleed: "30%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "pointless",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/17/9x19ripimg.png",
        _id: uuid()
    },
    {
        name: "QuakeMaker",
        gauge: "9x19mm",
        type: "Round",
        damage: 85,
        penPower: 8,
        armorDmg: "22%",
        accuracy: "+10%",
        recoil: "+10%",
        fragChance: "10%",
        lightBleed: "15%",
        heavyBleed: "22%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/f3/9x19QMview.png",
        _id: uuid()
    },
    {
        name: "PSO gzh",
        gauge: "9x19mm",
        type: "Round",
        damage: 59,
        penPower: 10,
        armorDmg: "32%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/83/9x19IMAGE.png",
        _id: uuid()
    },
    {
        name: "Luger CCI",
        gauge: "9x19mm",
        type: "Round",
        damage: 70,
        penPower: 10,
        armorDmg: "38%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "20%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/43/Cciimage.png",
        _id: uuid()
    },
    {
        name: "T gzh",
        gauge: "9x19mm",
        type: "Round",
        damage: 58,
        penPower: 14,
        armorDmg: "33%",
        accuracy: "-5%",
        recoil: "-6%",
        fragChance: "15%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "slightly effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/83/9x19IMAGE.png",
        _id: uuid()
    },
    {
        name: "Pst gzh",
        gauge: "9x19mm",
        type: "Round",
        damage: 54,
        penPower: 20,
        armorDmg: "33%",
        accuracy: "",
        recoil: "",
        fragChance: "15%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "magdump only",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/83/9x19IMAGE.png",
        _id: uuid()
    },
    {
        name: "AP 6.3",
        gauge: "9x19mm",
        type: "Round",
        damage: 52,
        penPower: 30,
        armorDmg: "48%",
        accuracy: "",
        recoil: "",
        fragChance: "5%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "effective",
            lvl5: "magdump only",
            lvl6: "its possible but unlikely"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/a3/9x19ap_ins.png",
        _id: uuid()
    },
    {
        name: "PBP gzh",
        gauge: "9x19mm",
        type: "Round",
        damage: 52,
        penPower: 39,
        armorDmg: "53%",
        accuracy: "+5%",
        recoil: "+15%",
        fragChance: "5%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c9/9x197N31view.png",
        _id: uuid()
    },
    {
        name: "RIP",
        gauge: ".45 ACP",
        type: "Round",
        damage: 137,
        penPower: 3,
        armorDmg: "12%",
        accuracy: "-5%",
        recoil: "",
        fragChance: "100%",
        lightBleed: "30%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "its possible but unlikely",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/1b/.45_RIP_View.png",
        _id: uuid()
    },
    {
        name: "Hydra-Shok",
        gauge: ".45 ACP",
        type: "Round",
        damage: 105,
        penPower: 13,
        armorDmg: "30%",
        accuracy: "",
        recoil: "",
        fragChance: "50%",
        lightBleed: "",
        heavyBleed: "30%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "slighly effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/64/.45_HS_View.png",
        _id: uuid()
    },
    {
        name: "Lasermatch FMJ",
        gauge: ".45 ACP",
        type: "Round",
        damage: 80,
        penPower: 19,
        armorDmg: "37%",
        accuracy: "+10%",
        recoil: "",
        fragChance: "1%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/80/.45LM_view.png",
        _id: uuid()
    },
    {
        name: "Match FMJ",
        gauge: ".45 ACP",
        type: "Round",
        damage: 76,
        penPower: 25,
        armorDmg: "36%",
        accuracy: "",
        recoil: "",
        fragChance: "1%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/51/.45_FMJ_View.png",
        _id: uuid()
    },
    {
        name: "AP",
        gauge: ".45 ACP",
        type: "Round",
        damage: 70,
        penPower: 38,
        armorDmg: "48%",
        accuracy: "-5%",
        recoil: "+7%",
        fragChance: "1%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "slightly effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/a8/45ACPAP_view_p.png",
        _id: uuid()
    },
    {
        name: "PE gzh",
        gauge: "9x21mm",
        type: "Round",
        damage: 80,
        penPower: 15,
        armorDmg: "63%",
        accuracy: "",
        recoil: "",
        fragChance: "35%",
        lightBleed: "15%",
        heavyBleed: "10",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/ec/SP12IMAGE.png",
        _id: uuid()
    },
    {
        name: "P gzh",
        gauge: "9x21mm",
        type: "Round",
        damage: 65,
        penPower: 18,
        armorDmg: "44%",
        accuracy: "",
        recoil: "",
        fragChance: "30%",
        lightBleed: "15%",
        heavyBleed: "10",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "slightly effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/0d/SP11IMAGE.png",
        _id: uuid()
    },
    {
        name: "PS gzh",
        gauge: "9x21mm",
        type: "Round",
        damage: 49,
        penPower: 35,
        armorDmg: "46%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "effective",
            lvl5: "slightly effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/3e/SP10IMAGE.png",
        _id: uuid()
    },
    {
        name: "BT gzh",
        gauge: "9x21mm",
        type: "Round",
        damage: 63,
        penPower: 39,
        armorDmg: "47%",
        accuracy: "-4",
        recoil: "-4",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c8/SP13IMAGE.png",
        _id: uuid()
    },
    {
        name: "R37.F",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 98,
        penPower: 8,
        armorDmg: "7%",
        accuracy: "",
        recoil: "",
        fragChance: "100%",
        lightBleed: "15%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/f7/R37F.png",
        _id: uuid()
    },
    {
        name: "SS198LF",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 74,
        penPower: 10,
        armorDmg: "15%",
        accuracy: "",
        recoil: "",
        fragChance: "80%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/aa/57x28mmSS198LF.png",
        _id: uuid()
    },
    {
        name: "R37.X",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 81,
        penPower: 11,
        armorDmg: "14%",
        accuracy: "",
        recoil: "",
        fragChance: "70%",
        lightBleed: "10%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/18/R37X.png",
        _id: uuid()
    },
    {
        name: "SS197SR",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 62,
        penPower: 20,
        armorDmg: "22%",
        accuracy: "",
        recoil: "",
        fragChance: "50%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "magdump only",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/8d/57x28mmSS197SR.png",
        _id: uuid()
    },
    {
        name: "L191",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 58,
        penPower: 33,
        armorDmg: "41%",
        accuracy: "-4%",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "slightly effective",
            lvl5: "magdump only",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e8/57x28mmL191.png",
        _id: uuid()
    },
    {
        name: "SB193",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 54,
        penPower: 35,
        armorDmg: "37%",
        accuracy: "+5%",
        recoil: "-24%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "effective",
            lvl5: "slightly effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/2/20/57x28mmSB193.png",
        _id: uuid()
    },
    {
        name: "SS190",
        gauge: "5.7x28mm",
        type: "Round",
        damage: 49,
        penPower: 37,
        armorDmg: "43%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/1d/57x28mmSS190.png",
        _id: uuid()
    },
    {
        name: "Action SX",
        gauge: "4.6x30mm",
        type: "Round",
        damage: 65,
        penPower: 18,
        armorDmg: "39%",
        accuracy: "",
        recoil: "",
        fragChance: "50%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "magdump only",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e9/4.6x30ActionImage.png",
        _id: uuid()
    },
    {
        name: "Subsonic SX",
        gauge: "4.6x30mm",
        type: "Round",
        damage: 45,
        penPower: 36,
        armorDmg: "46%",
        accuracy: "+10%",
        recoil: "-22%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "slightly effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/86/4.6x30SubsonicImage.png",
        _id: uuid()
    },
    {
        name: "FMJ SX",
        gauge: "4.6x30mm",
        type: "Round",
        damage: 43,
        penPower: 40,
        armorDmg: "41%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/44/4.6x30FMJImage.png",
        _id: uuid()
    },
    {
        name: "AP SX",
        gauge: "4.6x30mm",
        type: "Round",
        damage: 35,
        penPower: 53,
        armorDmg: "46%",
        accuracy: "",
        recoil: "+10%",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/8b/4.6x30APenImage.png",
        _id: uuid()
    },
    {
        name: "SP-5 gs",
        gauge: "9x39mm",
        type: "Round",
        damage: 68,
        penPower: 38,
        armorDmg: "52%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basiclly ignores",
            lvl2: "basiclly ignores",
            lvl3: "basiclly ignores",
            lvl4: "very effective",
            lvl5: "effecive",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/d/d1/SP5IMAGE.png",
        _id: uuid()
    },
    {
        name: "SP-6 gs",
        gauge: "9x39mm",
        type: "Round",
        damage: 58,
        penPower: 46,
        armorDmg: "60%",
        accuracy: "",
        recoil: "+10",
        fragChance: "10%",
        lightBleed: "10%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basiclly ignores",
            lvl2: "basiclly ignores",
            lvl3: "basiclly ignores",
            lvl4: "basiclly ignores",
            lvl5: "very effecive",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/34/SP6IMAGE.png",
        _id: uuid()
    },
    {
        name: "PAB-9 gs",
        gauge: "9x39mm",
        type: "Round",
        damage: 62,
        penPower: 48,
        armorDmg: "72%",
        accuracy: "-15",
        recoil: "+10",
        fragChance: "10%",
        lightBleed: "0%",
        heavyBleed: "0%",
        effectiveness: {
            lvl1: "basiclly ignores",
            lvl2: "basiclly ignores",
            lvl3: "basiclly ignores",
            lvl4: "basiclly ignores",
            lvl5: "basiclly ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/92/9x39_PAB-GS_View.png",
        _id: uuid()
    },
    {
        name: "SPP gs",
        gauge: "9x39mm",
        type: "Round",
        damage: 64,
        penPower: 50,
        armorDmg: "56%",
        accuracy: "+10",
        recoil: "+20",
        fragChance: "20%",
        lightBleed: "10%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "basiclly ignores",
            lvl2: "basiclly ignores",
            lvl3: "basiclly ignores",
            lvl4: "basiclly ignores",
            lvl5: "basiclly ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e5/7n9img.png",
        _id: uuid()
    },
    {
        name: "BP gs",
        gauge: "9x39mm",
        type: "Round",
        damage: 60,
        penPower: 55,
        armorDmg: "68%",
        accuracy: "+10",
        recoil: "+22",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basiclly ignores",
            lvl2: "basiclly ignores",
            lvl3: "basiclly ignores",
            lvl4: "basiclly ignores",
            lvl5: "basiclly ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e0/7n12img.png",
        _id: uuid()
    },
    {
        name: "Geksa",
        gauge: ".366 TKM",
        type: "Round",
        damage: 110,
        penPower: 14,
        armorDmg: "38%",
        accuracy: "",
        recoil: "",
        fragChance: "45%",
        lightBleed: "30",
        heavyBleed: "10",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/5e/GEKSAIMAGE.png",
        _id: uuid()
    },
    {
        name: "FMJ",
        gauge: ".366 TKM",
        type: "Round",
        damage: 98,
        penPower: 23,
        armorDmg: "48%",
        accuracy: "",
        recoil: "+10%",
        fragChance: "25%",
        lightBleed: "20%",
        heavyBleed: "25%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/89/TKMFMJIMAGE.png",
        _id: uuid()
    },
    {
        name: "EKO",
        gauge: ".366 TKM",
        type: "Round",
        damage: 73,
        penPower: 30,
        armorDmg: "40%",
        accuracy: "-10%",
        recoil: "-15%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "effective",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/4c/EKOIMAGE.png",
        _id: uuid()
    },
    {
        name: "AP-M",
        gauge: ".366 TKM",
        type: "Round",
        damage: 90,
        penPower: 42,
        armorDmg: "60%",
        accuracy: "-28%",
        recoil: "+35%",
        fragChance: "1%",
        lightBleed: "",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/5d/.366APView.png",
        _id: uuid()
    },
    {
        name: "SP",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 68,
        penPower: 11,
        armorDmg: "34%",
        accuracy: "+10%",
        recoil: "-15%",
        fragChance: "45%",
        lightBleed: "10%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/73/AKSPIMAGE.png",
        _id: uuid()
    },
    {
        name: "HP",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 74,
        penPower: 11,
        armorDmg: "20%",
        accuracy: "",
        recoil: "+5%",
        fragChance: "35%",
        lightBleed: "15%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "its possible but unlikely",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e1/AKHPIMAGE.png",
        _id: uuid()
    },
    {
        name: "PRS gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 60,
        penPower: 14,
        armorDmg: "28%",
        accuracy: "",
        recoil: "-5%",
        fragChance: "30%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/5f/AKPRSIMAGE.png",
        _id: uuid()
    },
    {
        name: "PRS gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 60,
        penPower: 14,
        armorDmg: "28%",
        accuracy: "",
        recoil: "-5%",
        fragChance: "30%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "magdump only",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/5f/AKPRSIMAGE.png",
        _id: uuid()
    },
    {
        name: "US gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 65,
        penPower: 15,
        armorDmg: "34%",
        accuracy: "",
        recoil: "-25%",
        fragChance: "10%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "slightly effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/31/AKUSIMAGE.png",
        _id: uuid()
    },
    {
        name: "FMJ",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 56,
        penPower: 21,
        armorDmg: "30%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "very effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/72/AKFMJIMAGE.png",
        _id: uuid()
    },
    {
        name: "T gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 57,
        penPower: 20,
        armorDmg: "38%",
        accuracy: "-5%",
        recoil: "-5%",
        fragChance: "16%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/88/AKTIMAGE.png",
        _id: uuid()
    },
    {
        name: "PS gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 50,
        penPower: 27,
        armorDmg: "35%",
        accuracy: "",
        recoil: "",
        fragChance: "40%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/a0/AKPSIMAGE.png",
        _id: uuid()
    },
    {
        name: "PP gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 48,
        penPower: 33,
        armorDmg: "32%",
        accuracy: "",
        recoil: "",
        fragChance: "17%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "slightly effective",
            lvl5: "magdump only",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/ea/AKPPIMAGE.png",
        _id: uuid()
    },
    {
        name: "BP gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 49,
        penPower: 35,
        armorDmg: "41%",
        accuracy: "",
        recoil: "",
        fragChance: "16%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "effective",
            lvl5: "slightly effective",
            lvl6: "its possible but unlikely"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/d/dc/AKBPIMAGE.png",
        _id: uuid()
    },
    {
        name: "BT gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 44,
        penPower: 37,
        armorDmg: "49%",
        accuracy: "-2%",
        recoil: "+3%",
        fragChance: "16%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/75/AKBTIMAGE.png",
        _id: uuid()
    },
    {
        name: "7N40",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 52,
        penPower: 44,
        armorDmg: "50%",
        accuracy: "+50%",
        recoil: "-20%",
        fragChance: "2%",
        lightBleed: "20%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/78/7N40_Full.png",
        _id: uuid()
    },
    {
        name: "BS gs",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 40,
        penPower: 51,
        armorDmg: "57%",
        accuracy: "-3%",
        recoil: "+10%",
        fragChance: "17%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/04/47BSIMAGE.png",
        _id: uuid()
    },
    {
        name: "PPBS gs Igolnik",
        gauge: "5.45x39mm",
        type: "Round",
        damage: 37,
        penPower: 62,
        armorDmg: "60%",
        accuracy: "",
        recoil: "+15%",
        fragChance: "2%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/4a/7n39img.png",
        _id: uuid()
    },
    {
        name: "Warmageddon",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 85,
        penPower: 3,
        armorDmg: "14%",
        accuracy: "+10%",
        recoil: "+10%",
        fragChance: "90%",
        lightBleed: "20%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "its possible but unlikely",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/4d/556warmageimage.png",
        _id: uuid()
    },
    {
        name: "HP",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 75,
        penPower: 9,
        armorDmg: "22%",
        accuracy: "",
        recoil: "",
        fragChance: "70%",
        lightBleed: "15%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "very effective",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/66/5.56x45IMAGE.png",
        _id: uuid()
    },
    {
        name: "MK 255 Mod 0 (RRLP)",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 60,
        penPower: 17,
        armorDmg: "32%",
        accuracy: "",
        recoil: "",
        fragChance: "3%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/1d/5.56x45_RRLP_image.png",
        _id: uuid()
    },
    {
        name: "MK 318 Mod 0 (SOST)",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 67,
        penPower: 20,
        armorDmg: "35%",
        accuracy: "+10%",
        recoil: "",
        fragChance: "15%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "slightly effective",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/ce/5.56x45MK318MODIMAGE.png",
        _id: uuid()
    },
    {
        name: "M856",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 55,
        penPower: 23,
        armorDmg: "34%",
        accuracy: "-2%",
        recoil: "-2%",
        fragChance: "33%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "slightly effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/2/2c/5.56x45_M856_image.png",
        _id: uuid()
    },
    {
        name: "FMJ",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 52,
        penPower: 24,
        armorDmg: "33%",
        accuracy: "+10%",
        recoil: "-5%",
        fragChance: "50%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/66/5.56x45IMAGE.png",
        _id: uuid()
    },
    {
        name: "M855",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 50,
        penPower: 28,
        armorDmg: "37%",
        accuracy: "-5%",
        recoil: "",
        fragChance: "40%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "magdump only",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/fb/5.56x45_M855_image.png",
        _id: uuid()
    },
    {
        name: "M856A1",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 51,
        penPower: 37,
        armorDmg: "52%",
        accuracy: "-1%",
        recoil: "+4%",
        fragChance: "33%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/3f/5.56x45_M856A1_image.png",
        _id: uuid()
    },
    {
        name: "M855A1",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 46,
        penPower: 45,
        armorDmg: "52%",
        accuracy: "-10%",
        recoil: "+5%",
        fragChance: "34%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/f5/M855A1.png",
        _id: uuid()
    },
    {
        name: "M995",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 40,
        penPower: 53,
        armorDmg: "58%",
        accuracy: "",
        recoil: "+8%",
        fragChance: "32%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/b0/M995.png",
        _id: uuid()
    },
    {
        name: "SSA AP",
        gauge: "5.56x45mm",
        type: "Round",
        damage: 36,
        penPower: 56,
        armorDmg: "64%",
        accuracy: "-6%",
        recoil: "+6%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/b7/SSA_AP.png",
        _id: uuid()
    },
    {
        name: "Whisper",
        gauge: ".300 Blackout",
        type: "Round",
        damage: 90,
        penPower: 14,
        armorDmg: "19%",
        accuracy: "+5%",
        recoil: "-5%",
        fragChance: "35%",
        lightBleed: "",
        heavyBleed: "+20%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "magdump only",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/44/Whisper.png",
        _id: uuid()
    },
    {
        name: "V-Max",
        gauge: ".300 Blackout",
        type: "Round",
        damage: 72,
        penPower: 20,
        armorDmg: "25%",
        accuracy: "+30%",
        recoil: "-10%",
        fragChance: "25%",
        lightBleed: "+22%",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "effective",
            lvl4: "slightly effective",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/5d/Vmax_big.png",
        _id: uuid()
    },
    {
        name: "BCP FMJ",
        gauge: ".300 Blackout",
        type: "Round",
        damage: 60,
        penPower: 29,
        armorDmg: "36%",
        accuracy: "",
        recoil: "",
        fragChance: "30%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "slightly effective",
            lvl5: "magdump only",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e9/BlackoutBPZ_view_.png",
        _id: uuid()
    },
    {
        name: "M62 Tracer",
        gauge: ".300 Blackout",
        type: "Round",
        damage: 54,
        penPower: 34,
        armorDmg: "40%",
        accuracy: "",
        recoil: "+5%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/09/300_BLK_M62_View.png",
        _id: uuid()
    },
    {
        name: "AP",
        gauge: ".300 Blackout",
        type: "Round",
        damage: 51,
        penPower: 45,
        armorDmg: "65%",
        accuracy: "",
        recoil: "+10%",
        fragChance: "30%",
        lightBleed: "15%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/35/BlackoutAP_View.png",
        _id: uuid()
    },
    {
        name: "HP",
        gauge: "7.62x39mm",
        type: "Round",
        damage: 87,
        penPower: 15,
        armorDmg: "35%",
        accuracy: "-5%",
        recoil: "",
        fragChance: "26%",
        lightBleed: "15%",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "its possible but unlikely",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c8/7.62x39HP_ins.png",
        _id: uuid()
    },
    {
        name: "US gzh",
        gauge: "7.62x39mm",
        type: "Round",
        damage: 56,
        penPower: 29,
        armorDmg: "42%",
        accuracy: "+5%",
        recoil: "-30%",
        fragChance: "8%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "slightly effective",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/ac/7.62x39US_ins.png",
        _id: uuid()
    },
    {
        name: "T-45M1 gzh",
        gauge: "7.62x39mm",
        type: "Round",
        damage: 62,
        penPower: 30,
        armorDmg: "46%",
        accuracy: "-4%",
        recoil: "-6%",
        fragChance: "12%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "slightly effective",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e8/7.62x39T45M_ins.png",
        _id: uuid()
    },
    {
        name: "PS gzh",
        gauge: "7.62x39mm",
        type: "Round",
        damage: 57,
        penPower: 32,
        armorDmg: "52%",
        accuracy: "",
        recoil: "",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "effective",
            lvl5: "slightly effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c4/7.62x39PS_ins.png",
        _id: uuid()
    },
    {
        name: "BP gzh",
        gauge: "7.62x39mm",
        type: "Round",
        damage: 58,
        penPower: 47,
        armorDmg: "63%",
        accuracy: "-3%",
        recoil: "+5%",
        fragChance: "12%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/c5/7.62x39BP_ins.png",
        _id: uuid()
    },
    {
        name: "MAI AP",
        gauge: "7.62x39mm",
        type: "Round",
        damage: 46,
        penPower: 58,
        armorDmg: "76%",
        accuracy: "-5%",
        recoil: "+10%",
        fragChance: "5%",
        lightBleed: "10%",
        heavyBleed: "10%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e7/7.62x39_MAI_AP.png",
        _id: uuid()
    },
    {
        name: "Ultra Nosler",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 107,
        penPower: 15,
        armorDmg: "20%",
        accuracy: "+10%",
        recoil: "-5%",
        fragChance: "70%",
        lightBleed: "20%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/aa/Ultra_Nosler.png",
        _id: uuid()
    },
    {
        name: "BCP FMJ",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 88,
        penPower: 31,
        armorDmg: "33%",
        accuracy: "",
        recoil: "-3%",
        fragChance: "25%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "magdump only",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/1d/BPZ_FMJ.png",
        _id: uuid()
    },
    {
        name: "TCW SP",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 60,
        penPower: 36,
        armorDmg: "40%",
        accuracy: "-8%",
        recoil: "-5%",
        fragChance: "20%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "magdump only",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/fd/TPZ_SP.png",
        _id: uuid()
    },
    {
        name: "M80",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 80,
        penPower: 41,
        armorDmg: "66%",
        accuracy: "",
        recoil: "",
        fragChance: "17%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/43/7.62x51_M80_banner.png",
        _id: uuid()
    },
    {
        name: "M62 Tracer",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 79,
        penPower: 44,
        armorDmg: "75%",
        accuracy: "-6%",
        recoil: "-5%",
        fragChance: "14%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/72/7.62x51_M62_banner.png",
        _id: uuid()
    },
    {
        name: "M61",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 70,
        penPower: 64,
        armorDmg: "83%",
        accuracy: "+3%",
        recoil: "+10%",
        fragChance: "13%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/7a/7.62x51_M61_banner.png",
        _id: uuid()
    },
    {
        name: "M993",
        gauge: "7.62x51mm",
        type: "Round",
        damage: 67,
        penPower: 70,
        armorDmg: "85%",
        accuracy: "+3%",
        recoil: "+8%",
        fragChance: "13%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/3d/7.62x51M933view.png",
        _id: uuid()
    },
    {
        name: "T-46M",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 82,
        penPower: 41,
        armorDmg: "83%",
        accuracy: "-1%",
        recoil: "-5%",
        fragChance: "18%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e7/7.62x39_MAI_AP.png",
        _id: uuid()
    },
    {
        name: "T-46M",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 82,
        penPower: 41,
        armorDmg: "83%",
        accuracy: "-1%",
        recoil: "-5%",
        fragChance: "18%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/59/T46M.png",
        _id: uuid()
    },
    {
        name: "R LPS gzh",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 81,
        penPower: 42,
        armorDmg: "78%",
        accuracy: "",
        recoil: "",
        fragChance: "18%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/68/7.62x54RIMAGE.png",
        _id: uuid()
    },
    {
        name: "R PS gzh",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 86,
        penPower: 45,
        armorDmg: "84%",
        accuracy: "+10%",
        recoil: "+8%",
        fragChance: "8%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/68/7.62x54RIMAGE.png",
        _id: uuid()
    },
    {
        name: "BT gzh",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 78,
        penPower: 59,
        armorDmg: "87%",
        accuracy: "-2%",
        recoil: "-4%",
        fragChance: "8%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/0d/7bt1.png",
        _id: uuid()
    },
    {
        name: "SNB",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 75,
        penPower: 62,
        armorDmg: "87%",
        accuracy: "",
        recoil: "+10%",
        fragChance: "8%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/6/68/7.62x54RIMAGE.png",
        _id: uuid()
    },
    {
        name: "BS",
        gauge: "7.62x54mm",
        type: "Round",
        damage: 72,
        penPower: 70,
        armorDmg: "88%",
        accuracy: "",
        recoil: "",
        fragChance: "8%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/84/7N37.png",
        _id: uuid()
    },
    {
        name: "TAC-x",
        gauge: ".338 Lapua Magnum",
        type: "Round",
        damage: 196,
        penPower: 18,
        armorDmg: "55%",
        accuracy: "+10%",
        recoil: "+5%",
        fragChance: "50%",
        lightBleed: "80%",
        heavyBleed: "50%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "effective",
            lvl3: "slightly effective",
            lvl4: "its possible but unlikely",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/8b/338tacx.png",
        _id: uuid()
    },
    {
        name: "UCW",
        gauge: ".338 Lapua Magnum",
        type: "Round",
        damage: 142,
        penPower: 32,
        armorDmg: "70%",
        accuracy: "-5%",
        recoil: "",
        fragChance: "60%",
        lightBleed: "50%",
        heavyBleed: "40%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "very effective",
            lvl5: "effective",
            lvl6: "magdump only"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/76/338_upz_view.png",
        _id: uuid()
    },
    {
        name: "FMJ",
        gauge: ".338 Lapua Magnum",
        type: "Round",
        damage: 122,
        penPower: 47,
        armorDmg: "83%",
        accuracy: "",
        recoil: "",
        fragChance: "20%",
        lightBleed: "35%",
        heavyBleed: "50%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "very effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/a/ae/338fmj.png",
        _id: uuid()
    },
    {
        name: "AP",
        gauge: ".338 Lapua Magnum",
        type: "Round",
        damage: 115,
        penPower: 79,
        armorDmg: "89%",
        accuracy: "",
        recoil: "+10%",
        fragChance: "13%",
        lightBleed: "20%",
        heavyBleed: "55%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "basically ignores",
            lvl6: "basically ignores"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/f/f0/338ap.png",
        _id: uuid()
    },
    {
        name: "PS12A",
        gauge: "12.7x55mm",
        type: "Round",
        damage: 165,
        penPower: 10,
        armorDmg: "22%",
        accuracy: "-15%",
        recoil: "-12%",
        fragChance: "70%",
        lightBleed: "35%",
        heavyBleed: "30%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "pointless",
            lvl3: "pointless",
            lvl4: "pointless",
            lvl5: "pointless",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/c/cd/12.7x55_PS12A.png",
        _id: uuid()
    },
    {
        name: "PS12",
        gauge: "12.7x55mm",
        type: "Round",
        damage: 115,
        penPower: 28,
        armorDmg: "60%",
        accuracy: "+10%",
        recoil: "",
        fragChance: "30%",
        lightBleed: "30%",
        heavyBleed: "20%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "very effective",
            lvl4: "magdump only",
            lvl5: "its possible but unlikely",
            lvl6: "pointless"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/3/38/12.7x55_PS12.png",
        _id: uuid()
    },
    {
        name: "PS12B",
        gauge: "12.7x55mm",
        type: "Round",
        damage: 102,
        penPower: 46,
        armorDmg: "57%",
        accuracy: "",
        recoil: "+15%",
        fragChance: "30%",
        lightBleed: "",
        heavyBleed: "15%",
        effectiveness: {
            lvl1: "basically ignores",
            lvl2: "basically ignores",
            lvl3: "basically ignores",
            lvl4: "basically ignores",
            lvl5: "very effective",
            lvl6: "effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/d/df/12.7x55_PS12B.png",
        _id: uuid()
    },
    {
        name: "M576 (MP-APERS) Grenade",
        gauge: "40x46mm",
        type: "Grenade launcher cartridge",
        damage: 2400,
        penPower: 5,
        armorDmg: "95%",
        accuracy: "",
        recoil: "",
        fragChance: "0%",
        lightBleed: "",
        heavyBleed: "",
        effectiveness: {
            lvl1: "very effective",
            lvl2: "slightly effective",
            lvl3: "slightly effective",
            lvl4: "slightly effective",
            lvl5: "slightly effective",
            lvl6: "slightly effective"
        },
        img: "https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/e/e1/M5763D.png",
        _id: uuid()
    }
]

module.exports = ammo;